name: Build Resume

on:
  push:
    branches:
      - main
    paths:
      - "**.tex"
      - "**.yml"
      - "**.cls"
      - "public/sitedata/**.json"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-resume:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install node dependencies
        run: npm install

      - name: Update resume LaTeX file
        run: npm run compile-tex-resume

      - name: Create LaTeX pdf document
        run: |
          latexmk -pdf -outdir=public -interaction=nonstopmode public/resume.tex

      - name: Update formatting
        run: npm run lint

      - name: Configure Git
        run: |
          git config --global --add safe.directory /__w/shuklabhay.github.io/shuklabhay.github.io
          git config --global user.name "shuklabhay/portfolio"
          git config --global user.email "portfolio[bot]@shuklabhay.github.io"

      - name: Commit changes to resume.tex and resume.pdf
        run: |
          git add public/resume/resume.pdf public/resume/resume.tex
          git pull
          git commit -m "Build Resume PDF"
          git push

      - name: Redeploy page
        if: github.event_name == 'workflow_dispatch'
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/shuklabhay/shuklabhay.github.io/dispatches \
          -d '{"event_type": "deploy-github-page"}'
