name: Build Resume

on:
  push:
    branches:
      - main
    paths:
      - "**.tex"
      - "**.yml"
      - "**.cls"
      - "public/sitedata/**.json"
  workflow_dispatch:

permissions:
  contents: write
  actions: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-resume:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install node dependencies
        run: npm install

      - name: Update resume LaTeX file
        run: npm run compile-tex-resume

      - name: Create LaTeX pdf document
        run: |
          latexmk -pdf -outdir=public -interaction=nonstopmode public/resume.tex

      - name: Update formatting
        run: npm run lint

      - name: Trigger production deploy
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPOSITORY: ${{ github.repository }}
          TARGET_REF: ${{ github.ref_name }}
        run: |
          curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$GH_REPOSITORY/actions/workflows/deploy.yml/dispatches \
            -d "{\"ref\":\"$TARGET_REF\"}"
